### ISSUE TITLE
Bad.

### ISSUE THREAD

**Issue by ghost** [Planeflyer11/Piecacuator.github.io#1]
It's bad.

**Comment by ghost** [comment]
@Planeflyer11 It's Bad.

**Comment by ghost** [comment]
It's still bad.

**Comment by ghost** [comment]
@Planeflyer11 It is even more bad.

**Comment by ghost** [comment]
@Planeflyer11 It's 9:35 pm but here I am saying it's bad.

**Comment by ghost** [comment]
@Planeflyer11 I'm getting sleep :)

**Comment by Planeflyer11** [comment]
nein

**Comment by ghost** [comment]
It's still bad though
